- module-name: 'yt_dlp.extractor.lazy_extractors'
  anti-bloat:
    - description: 'remove lazy_extractors'
      module_code: |
        pass

- module-name: 'ytmusicapi'
  data-files:
    dest_path: '.'
    dirs:
      - 'locales'